### ISSUE TITLE
Expected Span or SpanContext, got NULL

### ISSUE THREAD

**Issue by svillega** [jukylin/jaeger-php#88]
Hi,

I'm getting this error after using the next two lines

$spanContext = $tracer->extract(Formats\TEXT_MAP, $_SERVER);
$serverSpan = $tracer->startSpan('span-name', ['child_of' => $spanContext]);

Fatal error: Uncaught OpenTracing\Exceptions\InvalidSpanOption: Invalid child_of option. Expected Span or SpanContext, got NULL

My setup is 
"jukylin/jaeger-php" : "^2.1.1-beta",
"opentracing/opentracing":"1.0.0-beta5"

**Comment by jukylin** [comment]
#81 # @cawolf #

**Comment by svillega** [comment]
Fixed using "jukylin/jaeger-php": "2.0.9-beta"

**Comment by cawolf** [comment]
I would consider this a bug in regards to the opentracing specification. The specification clearly states:
* `extract()` [may return null](https://github.com/opentracing/opentracing-php/blob/1.0.0-beta5/src/OpenTracing/Tracer.php#L86-L96)
* `startSpan()` [may throw a](https://github.com/opentracing/opentracing-php/blob/1.0.0-beta5/src/OpenTracing/Tracer.php#L63-L72) `InvalidSpanOption` (which has a named constructor for [invalid references, such as null](https://github.com/opentracing/opentracing-php/blob/1.0.0-beta5/src/OpenTracing/Exceptions/InvalidSpanOption.php#L40-L46))

So I would suggest 2 things:
* @svillega : instead of downgrading, you should handle `null` results of `extract()` according to the specification and *not* pass it unchecked into `startSpan()`, as this should throw an exception
* @jukylin : we should alter this library to correctly throw the correct exception when `null` is passed

What do you think?

Best regards,
@cawolf

**Comment by jukylin** [comment]
I think is not friendly if engineer handle `null` results of `extract()`.
So I want to check the result in `startSpan()` when `null` is passed.
```php
if(array_search(null, $options) == "child_of"){
        $options = [];
};
```
you are right @cawolf , `startSpan()` can throw a InvalidSpanOption but not because the `null`

**Comment by cawolf** [comment]
Well actually, your library currently behaves like the opentracing specification is describing it, because you are utilizing `StartSpanOptions::create()`, from which the exception originally came from. I was wrong reopening this issue, but @svillega should still catch and handle the exception (which is declared in the opentracing interfaces) or explicitely check on null to avoid the error.

So no todo in your library, but this is a user error.

**Comment by jukylin** [comment]
@svillega  Reference [startActiveSpan](https://github.com/jukylin/jaeger-php/blob/master/example/HTTP2.php#L18)

**Comment by svillega** [comment]
@jukylin can you explain to me what's the difference between startSpan and startActiveSpan?
Thanks

**Comment by jukylin** [comment]
You can look here [startSpan](https://github.com/opentracing/opentracing-php/blob/1.0.0-beta5/src/OpenTracing/Tracer.php#L63-L72) and [startActiveSpan](https://github.com/opentracing/opentracing-php/blob/1.0.0-beta5/src/OpenTracing/Tracer.php#L61)
